language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly
    - hhvm

matrix:
  include:
    - php: 5.3
      dist: precise

before_script:
    - travis_retry composer install

script:
    - if [ $(phpenv version-name) >= "7.0" ]; then composer test;    fi
    - if [ $(phpenv version-name) <  "7.0" ]; then composer oldtest; fi

branches:
  except:
    - one-dot-two
